### ISSUE TITLE
Unable to attach function

### ISSUE THREAD

**Issue by faizanalhassan** [umihico/pythonista-chromeless#30]
Followed exact steps given in readme to run the readme.

 But got this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\repos\chromeless\chromeless\chromeless.py", line 24, in attach
    self.codes[method.__name__] = inspect.getsource(
  File "C:\Users\faizan\AppData\Local\Programs\Python\Python39\lib\inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\Users\faizan\AppData\Local\Programs\Python\Python39\lib\inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\faizan\AppData\Local\Programs\Python\Python39\lib\inspect.py", line 835, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```
I have not used sls earlier, just deployed to lambda directly, so maybe some steps are not written for devs who are unfamiliar with sls.

**Comment by umihico** [comment]
@faizanalhassan 

Thank you for reporting. I didn't know `inspect.getsource` can't work in interactive mode. I guess you can run if you save readme script on files. Could you try that?

#30 is not perfect solution, just telling people more friendly that you can't use this in interactive mode.

**Comment by faizanalhassan** [comment]
Thanks for your help. that error is gone.
However, the script is still not running. I am getting another error:
<pre><code>Function not found: arn:aws:lambda:<strong>us-west-2</strong>:<aws account id>:function:chromeless-server-prod</code></pre>
You can see the region its referring is `us-west-2`, but the command I ran was `sls deploy --region us-east-2`. Is there anything I am missing? Any env or updates in `serverless.yml`?

**Comment by faizanalhassan** [comment]
My bad, there was another npm package named `sls`, which was doing trouble. 
Uninstalled it.
Thanks again.

**Comment by faizanalhassan** [comment]
Lambda deployed successfully, but still getting same error:
`arn:aws:lambda:us-west-2:<aws account id>:function:chromeless-server-prod`
How do i tell Chromeless to target my region `us-east-2`

**Comment by umihico** [comment]
@faizanalhassan 
I'm glad to hear that the former problems are gone.

What output will you get if you execute `aws configure get region` in shell?

First, you need to deploy by `sls deploy --region us-east-2`.
Second, setting environmental variable works like `AWS_DEFAULT_REGION=us-west-2 python main.py`
Or, hard-coding in script is also possible like below.

```python
from chromeless import Chromeless
import boto3 # This
boto3.setup_default_session(region_name='us-east-2') # This

def get_title(self, url):
    self.get(url)
    return self.title

chrome = Chromeless()
chrome.attach(get_title)
print(chrome.get_title("https://example.com"))
```

If you don't mind setting `us-east-2` as your default region so far, I'd recommend `aws configure set region us-east-2` and above modifications are probably not necessary, but deployment.

**Comment by faizanalhassan** [comment]
Yeah, actually I have multiple AWS profiles, so that might be causing this. I also set `region_name` in boto3, but the env way you shared is better `AWS_DEFAULT_REGION`, so will try that.
As always again thanks.

**Comment by faizanalhassan** [comment]
However, I suggest to accept aws key, secret and region in `Chromeless.__init__`, and by default it would be coming through env or AWS local config. If you agree with this suggestion, I can do these updates and create a PR.

**Comment by umihico** [comment]
Yes, I agree with your idea and PR is always welcome, thank you!

Instead of accepting credentials directly, I think `__init__` should accept 'session', then session can take care of credentials or profile

```python
from boto3.session import Session

session = Session(aws_access_key_id='<YOUR ACCESS KEY ID>',
                  aws_secret_access_key='<YOUR SECRET KEY>',
                  region_name='<REGION NAME>')
# or
session = Session(profile_name='<YOUR_PROFILE_NAME>')
```

**Comment by faizanalhassan** [comment]
Ok doing with session object. Will update you in a day or two. Thanks for accepting my contributions.
