### ISSUE TITLE
Should accept region, credentials, and profiles

### ISSUE THREAD

**Issue by umihico** [umihico/pythonista-chromeless#33]
Splited issue from #30
@faizanalhassan

**Comment by faizanalhassan** [comment]
Will share updates in a day or two.

**Comment by umihico** [comment]
Thank you! You can skip documentation and tests. Especially tests, it's kind of complicated for other developers.

**Comment by faizanalhassan** [comment]
Yeah, will skip it for now. But would love to learn these automated tests.
